"""Updated table

Revision ID: 65bafeaf344b
Revises: 705fcaa22de1
Create Date: 2025-05-25 10:45:58.585629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65bafeaf344b'
down_revision: Union[str, None] = '705fcaa22de1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_events_user_session'), table_name='auth_events')
    op.drop_table('auth_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_events',
    sa.Column('auth_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('success', 'failure', name='authstatusenum'), autoincrement=False, nullable=False),
    sa.Column('auth_method', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], name=op.f('auth_events_session_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('auth_events_user_id_fkey')),
    sa.PrimaryKeyConstraint('auth_id', name=op.f('auth_events_pkey'))
    )
    op.create_index(op.f('ix_auth_events_user_session'), 'auth_events', ['user_id', 'session_id'], unique=False)
    # ### end Alembic commands ###
