"""remove sessiion id from feedback help request

Revision ID: 69b7fee72176
Revises: c7c4a99781ae
Create Date: 2025-05-24 23:02:20.676141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69b7fee72176'
down_revision: Union[str, None] = 'c7c4a99781ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fallback_help_user_session'), table_name='fallback_help_requests')
    op.create_index('ix_fallback_help_user', 'fallback_help_requests', ['user_id'], unique=False)
    op.drop_constraint(op.f('fallback_help_requests_session_id_fkey'), 'fallback_help_requests', type_='foreignkey')
    op.drop_column('fallback_help_requests', 'session_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fallback_help_requests', sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fallback_help_requests_session_id_fkey'), 'fallback_help_requests', 'sessions', ['session_id'], ['session_id'])
    op.drop_index('ix_fallback_help_user', table_name='fallback_help_requests')
    op.create_index(op.f('ix_fallback_help_user_session'), 'fallback_help_requests', ['user_id', 'session_id'], unique=False)
    # ### end Alembic commands ###
