"""add sessiion id in feedback help request

Revision ID: 705fcaa22de1
Revises: fd4c0eb9d3ec
Create Date: 2025-05-24 23:34:09.720657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '705fcaa22de1'
down_revision: Union[str, None] = 'fd4c0eb9d3ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fallback_help_user'), table_name='fallback_help_requests')
    op.create_index('ix_fallback_help_user', 'fallback_help_requests', ['user_id', 'session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fallback_help_user', table_name='fallback_help_requests')
    op.create_index(op.f('ix_fallback_help_user'), 'fallback_help_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###
