"""add password column to user table

Revision ID: c7c4a99781ae
Revises: 0a55da69d28c
Create Date: 2025-05-24 15:08:59.516495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7c4a99781ae'
down_revision: Union[str, None] = '0a55da69d28c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fallback_help_requests', 'notes',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_column('fallback_help_requests', 'intent')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fallback_help_requests', sa.Column('intent', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('fallback_help_requests', 'notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
