"""add sessiion id in feedback help request

Revision ID: fd4c0eb9d3ec
Revises: 69b7fee72176
Create Date: 2025-05-24 23:30:33.682049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd4c0eb9d3ec'
down_revision: Union[str, None] = '69b7fee72176'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fallback_help_requests', sa.Column('session_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'fallback_help_requests', 'sessions', ['session_id'], ['session_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fallback_help_requests', type_='foreignkey')
    op.drop_column('fallback_help_requests', 'session_id')
    # ### end Alembic commands ###
